// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nicommerce.DataAccess.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nicommerce.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250419075131_SeedProductsTable")]
    partial class SeedProductsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nicommerce.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "SciFi"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "History"
                        });
                });

            modelBuilder.Entity("Nicommerce.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ListPrice")
                        .HasColumnType("double precision");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "John Doe",
                            Description = "A comprehensive guide to C# programming.",
                            ISBN = "978-1234567890",
                            ListPrice = 49.990000000000002,
                            Price = 39.990000000000002,
                            Title = "C# Programming"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Jane Smith",
                            Description = "Learn how to build web applications using ASP.NET Core.",
                            ISBN = "978-0987654321",
                            ListPrice = 59.990000000000002,
                            Price = 49.990000000000002,
                            Title = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Alice Johnson",
                            Description = "Master data access with Entity Framework.",
                            ISBN = "978-1122334455",
                            ListPrice = 39.990000000000002,
                            Price = 29.989999999999998,
                            Title = "Entity Framework"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Bob Brown",
                            Description = "Explore LINQ and its powerful features.",
                            ISBN = "978-2233445566",
                            ListPrice = 29.989999999999998,
                            Price = 19.989999999999998,
                            Title = "LINQ in Action"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Charlie Green",
                            Description = "Understand and apply design patterns in software development.",
                            ISBN = "978-3344556677",
                            ListPrice = 69.989999999999995,
                            Price = 59.990000000000002,
                            Title = "Design Patterns"
                        },
                        new
                        {
                            Id = 6,
                            Author = "David White",
                            Description = "Learn about microservices and how to implement them.",
                            ISBN = "978-4455667788",
                            ListPrice = 79.989999999999995,
                            Price = 69.989999999999995,
                            Title = "Microservices Architecture"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
